apiVersion: krew.googlecontainertools.github.com/v1alpha1
kind: Plugin
metadata:
  name: foo
spec:
  version: "v0.0.1"
  shortDescription: Foo is a demo plugin
  description: |
    This is an amazing demo
    plugin. It is meant to be full
    of inspiring ideas to start
    writing plugins!
  caveats: |
    This plugin needs the following programs:
    * env
  platforms:
  - head: https://github.com/lbb/kubectl-plugin-demo/archive/master.zip
    files:
    - from: "*/*"
      to: "."
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]} 

